travis:
  secure:
    BINSTAR_TOKEN: NiDTpex8sXYLUW6VNyKaK5kuHH+Xe8kUzL8QMaDG+YrpfwT1qfxHYPLbcWeiDJOrON/0lsICgqeYq26pC8BsaqkdJtoEoIZldiso6eWcm+GMRBtX+8lpqzNK0x+VuEXKmhbs8XhjjaUotPLFv53pBjvwOyUTW8P6DEvjIrmdK0obp/Ux6+PZ5aqd17Mv/pggvmxqY19B3xPEdOdHpFWZYhOGGv95iLMq4TFkfEybKI3TrPbNGCyelco/owJHQeTq7VkqYN9QN32/YgboZgobKI0CK7/VEghLgTh5/WqMEIjFgl1Ge+6WMDk7qJKExV5Gs5qtNhy3DGV8eiJ+Rn3nD8UOrD4lUZTkESIOZ82QfVzv0u7JeFWXlgeADIkGEJpgjAQ9MJfxcz0+hiG+IO0iiheTJkhAhz2AS8LK7dYXTAAOvZHIyJPAqNivN26tb6WJ+hbVKG0ut+SYDbQljMTqKr0zNLb5hcIW75tx7exoJuIyOYk3rxm4B4k8CiX1YscQl24EpfBf1OZloFXDGbVs6mYoMLdn2RZuVfKDor/cInH1fV4gx63tTJHNrI7opU/iC0MmKyfJIWdgv2G2XainR6wsv5DHDDZ04YkyV1sTU+b/aDuG3zfNyz7rS+Ncus9VGkG7t/zjUoR662oOtgKGMyk/iVIQYD6S6OVwI9nYYzE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
